# -*- coding: utf-8 -*-
"""Resume_screening.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qyO3tPDcffUMQB3-XRAQ8QtgPmQx1M6s

## Resume Screening
"""





"""##  STEP 1 — Install Required Libraries"""

pip install pandas numpy scikit-learn nltk matplotlib seaborn wordcloud

"""##  STEP 2 — Load and Explore the Dataset"""

import pandas as pd

# Load the dataset
df = pd.read_csv("resume_dataset.csv")

# See first 5 rows
print(df.head())

# Check shape (rows, columns)
print("Shape:", df.shape)

# Check label distribution
print(df['label'].value_counts())

"""## STEP 3 — Text Preprocessing (The Heart of NLP)"""

import re
import nltk
nltk.download('stopwords')
nltk.download('punkt')

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()

def preprocess_text(text):
    # Step 1: Lowercase everything
    text = text.lower()

    # Step 2: Remove special characters and numbers
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # Step 3: Tokenize (split into words)
    tokens = text.split()

    # Step 4: Remove stopwords (like 'the', 'is', 'in')
    tokens = [word for word in tokens if word not in stop_words]

    # Step 5: Stemming (reduce words to root: 'working' → 'work')
    tokens = [stemmer.stem(word) for word in tokens]

    # Join back to string
    return ' '.join(tokens)

# Apply preprocessing to all resumes
df['cleaned_text'] = df['resume_text'].apply(preprocess_text)

print(df['cleaned_text'][0])  # See the cleaned version

"""## STEP 4 — Visualize with Word Cloud

"""

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Word cloud for Selected candidates
selected_text = ' '.join(df[df['label'] == 'Selected']['cleaned_text'])
wc = WordCloud(width=800, height=400, background_color='white').generate(selected_text)

plt.figure(figsize=(10, 5))
plt.imshow(wc)
plt.axis('off')
plt.title("Top Words in Selected Resumes")
plt.show()

"""## STEP 5 — Feature Extraction using TF-IDF"""

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=500)  # Use top 500 important words

X = tfidf.fit_transform(df['cleaned_text'])  # Feature matrix
y = df['label']                               # Labels (Selected/Rejected)

print("Feature matrix shape:", X.shape)  # (40, 500)
print("Top features:", tfidf.get_feature_names_out()[:20])

"""## STEP 6 — Split Data into Train and Test"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,       # 20% for testing
    random_state=42      # For reproducibility
)

print("Train size:", X_train.shape[0])
print("Test size:", X_test.shape[0])

"""## STEP 7 — Train a Machine Learning Model"""

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Train the model
model = MultinomialNB()
model.fit(X_train, y_train)

# Predict on test data
y_pred = model.predict(X_test)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

"""## STEP 8 — Confusion Matrix (Visual Evaluation)"""

import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred, labels=['Selected', 'Rejected'])

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Selected', 'Rejected'],
            yticklabels=['Selected', 'Rejected'])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix - Resume Screening")
plt.show()

"""## STEP 9 — Try on a New Resume (Prediction)"""

new_resume = """
Experienced data scientist with 4 years in NLP and machine learning.
Proficient in Python, scikit-learn, TensorFlow, and BERT.
Worked on text classification and sentiment analysis projects.
M.Tech in Computer Science from IIT.
"""

# Preprocess and predict
cleaned = preprocess_text(new_resume)
vectorized = tfidf.transform([cleaned])
prediction = model.predict(vectorized)

print("Prediction:", prediction[0])

"""## STEP 10 — Try Other Models (Bonus)"""

from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

# Logistic Regression
lr = LogisticRegression()
lr.fit(X_train, y_train)
print("Logistic Regression Accuracy:", accuracy_score(y_test, lr.predict(X_test)))

# Support Vector Machine
svm = LinearSVC()
svm.fit(X_train, y_train)
print("SVM Accuracy:", accuracy_score(y_test, svm.predict(X_test)))

